### ISSUE TITLE
Type 'SwiftToastStyle?' has no member 'aboveNavigationBar'

### ISSUE THREAD

**Issue by josselin-oudry** [damboscolo/SwiftToast#13]
Hi Daniele,

Thanks for making SwiftToast!

I was looking for a way to display the toast right below the navigation bar. Reading your documentation it seems like the SwiftToastStyle I was looking for is .aboveNavigationBar.
First thing is I don't quite understand the naming of this style as the toast clearly is presented below the navigation bar.
Second thing is that using the pod install, and then trying to use the .aboveNavigationBar style the swift compiler throws an error:
`Type 'SwiftToastStyle?' has no member 'aboveNavigationBar'` 

Eventually for this style I would love to be able to set a minimal height for the toast view that is for example 44pts.

Thanks again and have a great weekend :-)

Joss.

**Comment by damboscolo** [comment]
Hey,

Thank you for the feedback 😊

I did that toast based in my apps uses, I like so much when someone finds something to improve the library.

So, I intent to adjust those things this weekend!
I will send you a email when I finished.

Best regards,
Daniele Boscolo.

**Comment by damboscolo** [comment]
I intent*
Sorry 😂

**Comment by josselin-oudry** [comment]
Hehe... thanks for not pretending 😀

**Comment by damboscolo** [comment]
Library has been updated!
Write again if you find anything else. 😁

**Comment by josselin-oudry** [comment]
Amazingly fast and perfect update! Obrigado Daniele 😀

PS: I don't know if you've noticed my other email regarding some typos in the documentation. You should write "`let toast`" instead of "`let test`". And also now "four styles" instead of "three styles" 😉

**Comment by damboscolo** [comment]
Thank you! Obrigada Josselin 😂

I didn't see this email, but I will fix those typos.

Thank you for the help!
