### ISSUE TITLE
Status bar is disappearing

### ISSUE THREAD

**Issue by ivan-tsaryov** [damboscolo/SwiftToast#15]
When I am using Swift Toast style .statusBar and "above status bar". Toast showing up over status bar. It's OK. But when toast is going away, there is no status bar. And later status bar showing up. How to make that status bar was always visible?

**Comment by damboscolo** [comment]
Sorry for the delay, are you still having this problem?

**Comment by ivan-tsaryov** [comment]
No. I found workaround: I add SwiftToastView at another UIWindow, that is above status bar. So, status bar is not disappearing

**Comment by damboscolo** [comment]
I had never seen this problem, did you have this problem in all versions of iOS?
I'll test it better and try to find a solution.

**Comment by ivan-tsaryov** [comment]
It's not a bug. It's normal, because SwiftToastView is presenting at UIWindow with same  [UIWindow level](https://developer.apple.com/documentation/uikit/uiwindowlevel) as UIStatusBar
